version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - go-final-postgres-data:/var/lib/postgresql/data


  redis:
    image: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://postgres:password@postgres/postgres'
      REDIS_URL: 'redis:6379'
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  go-final-postgres-data: